services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  _instanceof:
    Broadway\EventHandling\EventListener:
      tags:
        - { name: broadway.domain.event_listener }

  Broadway\EventStore\EventStore:
    alias: Broadway\EventStore\Dbal\DBALEventStore

  Broadway\EventStore\Dbal\DBALEventStore:
    arguments:
      - '@doctrine.dbal.default_connection'
      - '@broadway.serializer.payload'
      - '@broadway.serializer.metadata'
      - 'events'
      - false
      - '@broadway.uuid.converter'
