nelmio_api_doc:
    documentation:
        info:
            title: Task Tracker API
            description: Task Tracker API service
            version: 1.0.0
        areas:
            path_patterns:
                - ^/api/v1(?!/doc$)

        # Add a separate section for v2
        v2:
            documentation:
                info:
                    title: Task Tracker API (V2)
                    description: Task Tracker API service - Version 2
                    version: 2.0.0
            areas:
                path_patterns:
                    - ^/api/v2(?!/doc$)
