nelmio_api_doc:
    documentation:
        info:
            title: Task Tracker
            description: Task Tracker API service, where users can create and manage tasks
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns: # an array of regexps (document only routes under /api, except /api/doc)
            - ^/api(?!/doc$)
