parameters:
  # Microservice applications
  global.project.name: '%env(APP_PROJECT_NAME)%'
  global.acl.name: '%env(APP_ACL_NAME)%'
  #micro.service.name: '%env(APP_SERVICE_NAME)%'
  micro.service.name: 'micro-tracker'

  # App
  app.env: '%env(APP_ENV)%'
  app.root_path: !php/const ROOT_PATH
  app.secret: '%env(APP_SECRET)%'
  #app.version: '%env(APP_VERSION)%'
  app.version: '1.0.0'
  app.service_name: '%micro.service.name%'

  # PostgreSQL
  db.postgresql.host: '%env(APP_DATABASE_HOST)%'
  db.postgresql.port: "%env(APP_DATABASE_PORT)%"
  db.postgresql.dbname: '%env(APP_DATABASE_NAME)%'
  db.postgresql.user: '%env(APP_DATABASE_LOGIN)%'
  db.postgresql.password: '%env(APP_DATABASE_PASSWORD)%'

  # Enqueue (main configs)
  enqueue.queue.host: '%env(APP_RABBITMQ_HOST)%'
  enqueue.queue.port: '%env(APP_RABBITMQ_PORT)%'

  # Enqueue (application names)
  enqueue.client.prefix: '%global.project.name%'
  enqueue.app.name: '%micro.service.name%'
  enqueue.app.name.global: '%global.acl.name%'

  # Enqueue (client applications)
  enqueue.topic.task: 'task'
  enqueue.topic.taskevent: 'taskevent'
  enqueue.topic.event: 'event'
  enqueue.topic.queueevent: 'queueevent'
  enqueue.topic.global.tracker: 'tracker.queueevent'

  # Enqueue (transport groups)
  enqueue.transport.group-id: '%micro.service.name%'
  enqueue.transport.group-id.global: '%global.project.name%' #@todo May be need to move into env vars in ci/cd

  # Nelmio
  nelmio.cors.allow_origin: '%env(APP_CORS_ALLOW_ORIGIN)%'

  # Temporal
#  temporal.host: '%env(TEMPORAL_CLI_ADDRESS)%'
