imports:
  - { resource: 'parameters.yaml' }

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  _instanceof:
    MicroModule\Base\Application\Tracing\TraceableInterface:
      calls:
        - setTracer: [ '@tracing.client' ]
        - setIsTracingEnabled: [ '%tracing.is_enabled%' ]

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  Micro\Tracker\Task\:
    resource: '../src/Task'

  MicroModule\Base\Application\EventSubscriber\RequestSubscriber:
    tags: [ kernel.event_listener ]
